### ISSUE TITLE
The plugin will look up the wrong chunk if the server does not use the default townblock size of 16

### ISSUE THREAD

**Issue by LlmDl** [QarthO/qTownyBiomeBlacklist#2]
https://github.com/QarthO/qTownyBiomeBlacklist/blob/e68377b9d5b02cb7e0ea823fefb2ef605a006c82/src/main/java/gg/quartzdev/qtownybiomeblacklist/listeners/TownyClaimListener.java#L53-L57

You may want to add a warning on startup when TownySettings.getTownBlockSize() is not 16. 

When it is 16 the TownBlocks and Chunks all line up.

If you want to add support for non-16 sized townblocks you can get the chunks via TownBlock.getWorldCoord().getChunks() which will get you a Collection<CompletableFuture<Chunk>>.

**Comment by QarthO** [comment]
Fixes this in 46cdf13

Just decided to disable the plugin if the server isn't using the default townblock size of 16. Will add support as needed. Currently only ~2% of servers are not using the default size.

Feel free to bug me if you'd like me to implement a fix
